changelog:
  exclude:
    labels:
      - ignore
    authors:
      - github-actions

  categories:
    - title: New Features 🎉
      labels:
        - enhancement
        - feature
    - title: Bug Fix 🛠️
      labels:
        - bug
        - fix
    - title: Misc Changes 🎨
      labels:
        - "*"
