name: Create a release pull request

on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Check if PR already exists
      - name: Check existence of release pull request
        run: echo "count=$(gh pr list -S 'Release in:title' -B master -s open | wc -l)" >> $GITHUB_OUTPUT
        id: check_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create PR if not exists
      - name: Create release pull request
        uses: octokit/request-action@v2.x
        if: steps.check_pr.outputs.count == 0
        with:
          route: POST /repos/:repository/pulls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_REPOSITORY: ${{ github.repository }}
          INPUT_TITLE: Preparing release pull request...
          INPUT_HEAD: staging
          INPUT_BASE: master
