name: Update current release PR

on:
  pull_request:
    branches:
      - master

jobs:
  update-release-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Get previous release
      - uses: octokit/request-action@v2.x
        id: get_prev_tag
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: darthrommy
          repo: calver-playground
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Generate release tag
      - id: get_relese_tag
        run: |
          today=$(date +'%Y.%m.%d')
          pre_release_date=$(echo ${{ fromJSON(steps.get_prev_tag.outputs.data).tag_name }} | awk -F'-' '{print $1}')
          pre_release_count=$(echo ${{ fromJSON(steps.get_prev_tag.outputs.data).tag_name }} | awk -F'-' '{print $2}')
          if [[ ! $pre_release_date = $today ]]; then
            echo "will be today's first release"
            pre_release_count=0
          fi
          echo "release_tag=$today-$(($pre_release_count + 1))" >> $GITHUB_OUTPUT

      # Generate release note
      - uses: octokit/request-action@v2.x
        id: generate_changelog
        with:
          route: POST /repos/{owner}/{repo}/releases/generate-notes
          owner: darthrommy
          repo: calver-playground
          tag_name: ${{ steps.get_release_tag.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Update PR
      - uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/pulls/{pull_number}
          owner: darthrommy
          repo: calver-playground
          pull_number: ${{ github.event.number }}
          title: ${{ steps.get_release_tag.outputs.release_tag }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
